# Generated by Django 5.0.1 on 2026-01-13 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('hint', models.TextField(blank=True, verbose_name='Подсказка')),
                ('example_code', models.TextField(blank=True, verbose_name='Пример кода')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в теме')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('description', models.TextField(verbose_name='Описание темы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('theory_content', models.TextField(blank=True, verbose_name='Теоретический материал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_classes', to=settings.AUTH_USER_MODEL, verbose_name='Создан администратором')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('test_results', models.JSONField(default=dict, verbose_name='Результаты тестов')),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка (%)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Отправка кода',
                'verbose_name_plural': 'Отправки кода',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('variable', 'Проверка переменной'), ('output', 'Проверка вывода'), ('contains', 'Содержит текст'), ('no_error', 'Без ошибок')], max_length=20, verbose_name='Тип теста')),
                ('variable_name', models.CharField(blank=True, max_length=100, verbose_name='Имя переменной')),
                ('expected_value', models.JSONField(verbose_name='Ожидаемое значение')),
                ('description', models.CharField(max_length=200, verbose_name='Описание теста')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Тестовый случай',
                'verbose_name_plural': 'Тестовые случаи',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.topic', verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Не пройдено')], default='not_started', max_length=20, verbose_name='Статус')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('best_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Лучший результат (%)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Прогресс ученика',
                'verbose_name_plural': 'Прогресс учеников',
                'unique_together': {('student', 'task')},
            },
        ),
        migrations.CreateModel(
            name='ClassTopicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='Доступ открыт')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class', verbose_name='Класс')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Открыт администратором')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Доступ к теме',
                'verbose_name_plural': 'Доступ к темам',
                'unique_together': {('class_obj', 'topic')},
            },
        ),
    ]
