# Generated by Django 5.0.1 on 2026-01-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код для выполнения')),
                ('test_cases', models.JSONField(default=list, verbose_name='Тестовые случаи')),
                ('results', models.JSONField(default=dict, verbose_name='Результаты выполнения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Оценка (%)')),
                ('execution_time', models.FloatField(default=0.0, verbose_name='Время выполнения (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполнение кода',
                'verbose_name_plural': 'Выполнения кода',
                'ordering': ['-created_at'],
            },
        ),
    ]
